version: "3.8"

services:
  app:
    build: .
    container_name: scan2class_app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=${MYSQL_URL}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - scan2class-network

  db:
    image: mysql:8.0
    container_name: scan2class_db
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./src/main/resources/database/mock.sql:/docker-entrypoint-initdb.d/mock.sql
    networks:
      - scan2class-network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

networks:
  scan2class-network:
    driver: bridge

volumes:
  db_data:
